# Mark Guerin
# This program is a demonstration of my knowledge of Python
import time

userName = input("Please enter your name...")
def cont():
    userCont = input("Would you like to continue? Y/N")
    if userCont == "Y" or userCont == "y":
        intro()
    if userCont == "N" or userCont == "n":
        exit
    else:
        print("Invalid input")
        cont()

def intro():
    print("Welcome " + userName + ", please select a demonstration.")
    print("1: Arithmetic Operators")
    print("2: Parameter Passing")
    print("3: Project Euler Problems")
    demo = int(input())
    if demo == 1:
        arithmetic()
        cont()
    elif demo == 2:
        param()
        cont()
    elif demo == 3:
        euler()
        cont()
    else:
        print("Invalid selection")
        time.sleep(1)
        intro()

def arithmetic():
    print("Welcome to this short quiz.")
    print("Type two numbers whose sum is 7.")
    num1 = float(input("Type first number: "))
    num2 = float(input("Type second number: "))
    if num1 + num2 == 7:
        print("Correct!")

    elif num1 + num2 != 7:
        print("Incorrect")
        
    time.sleep(1)
    print("Type two numbers whose difference is 4.")
    num1 = float(input("Type first number: "))
    num2 = float(input("Type second number: "))
    if num1 - num2 == 4:
        print("Correct!")

    elif num1 - num2 != 4:
        print("Incorrect")
        
    time.sleep(1)
    print("Type two numbers whose product is 18.")
    num1 = float(input("Type first number: "))
    num2 = float(input("Type second number: "))
    if num1 * num2 == 18:
        print("Correct!")
    
    elif num1 * num2 != 18:
        print("Incorrect")
        
    time.sleep(1)
    print("Type two numbers whose quotient is 4.")
    num1 = float(input("Type first number: "))
    num2 = float(input("Type second number: "))
    if num1 / num2 == 4:
        print("Correct!")

    elif num1 / num2 != 4:
        print("Incorrect")
    time.sleep(1)

def param():
    import random

    def getMessage(userNum, randNum):
        if userNum == randNum:
            return "You picked the same number as the computer!"
        elif userNum > randNum:
            return "Your number is higher than the computer's number."
        elif userNum < randNum:
            return "Your number is smaller than the computer's number."

    def main():
        userNum = int(input("Enter a number between 1 and 5: "))
        while userNum > 5 or userNum < 1:
            userNum = int(input("Invalid number. Enter a number between 1 and 5: "))
        randNum = random.randint(1,5)
        print("Computer number:", randNum)
        print("User number:", userNum)
        print(getMessage(userNum, randNum))

    main()

def euler():
    print("Questions are taken from projecteuler.com")
    print("Problem 1:")
    print("If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.")
    print("Find the sum of all the multiples of 3 or 5 below 1000.")
    answer = int(input("Answer:"))
    total = 0
    for x in range(1000):
        if (x % 3 == 0 or x % 5 == 0):
            total += x
    if answer == total:
        print("Correct!")
    else:
        print("Incorrect. The answer is", total)
    time.sleep(2)
    
    print("Problem 2:")
    print("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:")
    print("1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...")
    print("By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.")
    answer = int(input("Answer:"))
    x = 1
    y = 2
    total = 0
    while x < 4000000:
        if x % 2 == 0:
            total += x
        z = x + y
        x = y
        y = z
    if answer == total:
        print("Correct!")
    else:
        print("Incorrect. The answer is", total)
    time.sleep(2)

intro()
